name: SuperDiff
on:
  push:
    branches:
      - main
      - ci-*
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
        rails_appraisal:
          - rails_5_0
          - rails_5_1
          - rails_5_2
          - rails_6_0
          - no_rails
        rspec_appraisal:
          - rspec_lt_3_10
          - rspec_gte_3_10
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails_appraisal }}_${{ matrix.rspec_appraisal }}.gemfile
      JAVA_OPTS: "--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.security.cert=ALL-UNNAMED --add-opens=java.base/java.util.zip=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/javax.crypto=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.base/java.io=org.jruby.dist"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        id: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bin/ci/run-tests
  test_ruby_3:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
        rails_appraisal:
          - rails_6_0
          - rails_7_0
          - no_rails
        rspec_appraisal:
          - rspec_lt_3_10
          - rspec_gte_3_10
        exclude:
          - ruby: 3.2
            rails_appraisal: rails_6_0
          - rails_appraisal: rails_7_0
            rspec_appraisal: rspec_lt_3_10

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails_appraisal }}_${{ matrix.rspec_appraisal }}.gemfile
      JAVA_OPTS: "--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.security.cert=ALL-UNNAMED --add-opens=java.base/java.util.zip=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/javax.crypto=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.base/java.io=org.jruby.dist"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        id: set-up-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bin/ci/run-tests
